name: Satel-github-runner-status
description: Checks the status of a self-hosted runner

inputs:
  github-runner-token:
    description: Token that can read runner data of the organization
    required: true
  org-name: 
    description: Name of the organization
    required: true     

outputs:
  status:  
    description: 'Status of the runner'
    value:  ${{ steps.status-check.outputs.status }}
  each_runner_status:
    description: 'Status of individual runner'
    value:  ${{ steps.status-check.outputs.each_runner_status }}
    

runs:
  using: "composite"
  steps:
    - name: Check runner status
      id: status-check
      env: 
        RUNNER_NAMES: 'cosmicray beast bigbilly qa-vm'
        GITHUB_RUNNER_TOKEN: ${{ inputs.github-runner-token }}
        GITHUB_API_VERSION: '2022-11-28'
        ORG_NAME: ${{ inputs.org-name}}
      run: ${{ github.action_path }}/CheckStatus.sh 
      shell: bash
