name: Satel-github-runner-status
description: Checks the status of a self-hosted runner

inputs:
  runner-names:
    description: Name of the self-hosted runners
    required: true 
  github-admin-token:
    description: Token that can read runner data
    required: true
  github-api-version:
    description: Stable api version
    required: true  

outputs:
  status:  
    description: 'Status of the runner'
    value:  ${{ steps.status-check.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Check runner status
      id: status-check
      env: 
        RUNNER_NAMES: ${{ inputs.runner-names }}
        GITHUB_ADMIN_TOKEN: ${{ inputs.github-admin-token }}
        GITHUB_API_VERSION: ${{ inputs.github-api-version }}
      run: ${{ github.action_path }}/CheckStatus.sh 
      shell: bash
