name: Satel-github-runner-status
description: Checks the status of a self-hosted runner

inputs:
  github-admin-token:
    description: Token that can read runner data
    required: true
  org-name: 
    description: Name of the organization
    required: true     

outputs:
  status:  
    description: 'Status of the runner'
    value:  ${{ steps.status-check.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Check runner status
      id: status-check
      env: 
        RUNNER_NAMES: 'beast'
        GITHUB_ADMIN_TOKEN: ${{ inputs.github-admin-token }}
        GITHUB_API_VERSION: '2022-11-28'
        ORG_NAME: ${{ inputs.org-name}}
      run: ${{ github.action_path }}/CheckStatus.sh 
      shell: bash
